### ISSUE TITLE
tmpi spawning N different sessions of size 1

### ISSUE THREAD

**Issue by FabioLuporini** [Azrael3000/tmpi#1]
Hello,

first of all, let me say that ``tmpi`` is great :) or better, it could be !
I bumped into this issue -- instead of getting say 4 panes each pane running one rank of an `mpirun -n 4 ...` program, I get 4 independent processes running in the 4 panes.

I don't do anything particularly relevant -- I run it normally as ``tmpi 4 ...`` and that's what I get. With any MPI program, including a classic hello world.

Is there anything on top of your mind that could help me out, or that I could look at?

**Comment by FabioLuporini** [comment]
EDIT -- I see this is just a fork, so perhaps you won't be able to answer me :sunglasses:

**Comment by FabioLuporini** [comment]
update -- I think it's because the scripts assumes OpenMPI under the hood

**Comment by FabioLuporini** [comment]
update: definitely OpenMPI is expected, but it still doesn't work...

**Comment by Azrael3000** [comment]
Hi, yeah I just forked it an did some minor modifications. I run OpenMPI and never tried anything else. What MPI are you running? Feel free to submit a pull request if you manage to fix it. I currently have some issues on Ubuntu 18.04 with it and will try and have a look at it in the next couple of weeks.

**Comment by FabioLuporini** [comment]
yep, I was using mpich, while it does work with openmpi. I'll see if I can come up with a patch. Thanks!

**Comment by FabioLuporini** [comment]
What version of OpenMPI do you use? Have you tried 3.x ?

**Comment by Azrael3000** [comment]
I'm running 2.1.1, I suspect it's the same problem with 3.x so thanks for your patch. I will see if I can review it this weekend.

**Comment by FabioLuporini** [comment]
great, thanks, keep me posted

**Comment by Azrael3000** [comment]
Thanks for the patch. Any progress on mpich?

**Comment by FabioLuporini** [comment]
my pleasure. No, no progress on mpich. And to be fair, I won't be able to work on it for the next couple of weeks at least (you know, deadlines...). But I'll definitely keep you posted

**Comment by Azrael3000** [comment]
Since we made some progress on MPICH support with the `reptyr` inclusion I'm going to close this.
