### ISSUE TITLE
Support intelmpi?

### ISSUE THREAD

**Issue by johnomotani** [Azrael3000/tmpi#10]
`intelmpi` implements the MPICH specification (according to https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/mpi-library.html#gs.9dy1lr), but does not seem to work with `tmpi`.

I tried changing
https://github.com/Azrael3000/tmpi/blob/ae369dc3aca8a0059c647918eb70660f625b177c/tmpi#L46
to
```
mpich=$(mpirun --version |grep -i -e HYDRA -e Intel)
```
but I get strange module errors
```
manpath: warning: $MANPATH set, ignoring /etc/man_db.conf
[ERR] The following modulefiles are not provided by module profile 'profile/base':
[ERR]   + intel/pe-xe-2020--binary
[ERR]   + intelmpi/2020--binary
[ERR]   + mkl/2020--binary
[ERR] Suggestion: 'module unload intel/pe-xe-2020--binary intelmpi/2020--binary mkl/2020--binary'

Loading profile/base
  ERROR: can't read "errorCode": no such variable
```
These don't appear when using the openmpi module. Unfortunately this cluster doesn't have mpich.
Edit: I think similar errors do actually appear when using openmpi, but exection continues and they are covered up by panels being launched soon afterward.

I don't know what else to try - am happy to try some more debugging if anyone has suggestions?

**Comment by Azrael3000** [comment]
It looks to me if that is some configuration error on your cluster. If you run `mpirun --version` on your command line, do you get the same errors?

**Comment by johnomotani** [comment]
No, no errors from `mpirun` on the command line:
```
$ mpirun --version
Intel(R) MPI Library for Linux* OS, Version 2019 Update 9 Build 20200923 (id: abd58e492)
Copyright 2003-2020, Intel Corporation.
$ mpirun -np 2 ./a.out 
WARNING: release_mt library was used but no multi-ep feature was enabled. Please use release library instead.
Hello world from processor r000u07l02, rank 0 out of 2 processors
Hello world from processor r000u07l02, rank 1 out of 2 processors
```

**Comment by johnomotani** [comment]
I'm not sure whether the errors are related or not. It seems like the errors occur as a new shell is starting, before `.bashrc` is run. After they appear, the `.bashrc` is run, and the modules are loaded correctly. I actually end up with a terminal prompt in a single window in `tmux`, and `module list` shows everything loaded correctly.

**Comment by Azrael3000** [comment]
Ok so it's probably an issue with the module loading and the order of starting mpi commands. Can you check the branch by https://github.com/s417-lama/tmpi and let me know if that helps you?

**Comment by johnomotani** [comment]
Thanks @Azrael3000! With that branch I have a different error. The tmux screen prints
```
mpirun -n 2 /<mypath>/tmpi-s417-lama runmpi 2 /tmp/tmp.JZpJ2uyqDN gdb ./a.out
usage: split-window [-dhvP] [-c start-directory] [-F format] [-p percentage|-l size] [-t target-pane] [command]
usage: split-window [-dhvP] [-c start-directory] [-F format] [-p percentage|-l size] [-t target-pane] [command]
```
and then seems to be hanging.

**Comment by Azrael3000** [comment]
Hm.. it seems there is an issue with the line here:

https://github.com/s417-lama/tmpi/blob/master/tmpi#L77

maybe @s417-lama has an idea what the issue could be. Alternatively, it would be good if you could you could let us know what the variables (e.g.  `$window`) are set to

**Comment by s417-lama** [comment]
Seems like the env val `$window` exported [here](https://github.com/s417-lama/tmpi/blob/9ae59b63413536ba97cbd311aabb4fd96c51679c/tmpi#L159) is not passed to MPI processes.
How about passing `-envall` option to `mpirun`?

**Comment by Azrael3000** [comment]
@johnomotani can you try this?

**Comment by johnomotani** [comment]
Ah, I've just realised I was using `tmux 1.8`, which is pretty ancient. I've just compiled `tmux 3.2a` (and also `reptyer`). Now https://github.com/s417-lama/tmpi works!

**Comment by Azrael3000** [comment]
ok fantastic, we should implement a check then for old tmux versions. We will, in the medium term (end of the year) merge that branch into the master one, so I'm closing this issue as solved.
