### ISSUE TITLE
fail to use tmpi

### ISSUE THREAD

**Issue by nicolas-tardieu** [Azrael3000/tmpi#16]
Dear Azrael3000,

I am failing to use tmpi. I have a toy mpi program hat runs OK with : 
`mpirun -np 2 xterm -e gdb /tmp/fort`
But if I switch to : 
`tmpi  2   gdb /tmp/fort`
I see a tmux appear then disappear with a `[exited]` print on screen.

Is there a way to debug tmpi to see what is going wrong ?

Thanks,
Nicolas

**Comment by Azrael3000** [comment]
Hi Nicolas,

do you have `reptyr` installed? Also, I suppose you are starting `tmpi` from within a `tmux` session, is that correct?

Cheers,
Arno

**Comment by nicolas-tardieu** [comment]
Thank you very much for answering my question Arno.
No I do not have `reptyr` installed and I do not start `tmpi` from within a `tmux` session - is it how it shoud be used [I did not understand that from the manual] ?

**Comment by Azrael3000** [comment]
Yeah that should be the preferred way of using it, please give it a try and let me know.

**Comment by nicolas-tardieu** [comment]
Mmmmm... Here is what I did (`fort` is a toy mpi program) : 
[fresh terminal]
`> tmux`
`> mpirun -n 2 ./fort`
This runs fine.

[fresh terminal]
`> tmux`
`> tmpi 2 ./fort`
This fails with the following output : 
```
mpirun -n 2 --oversubscribe /home/myHome/local/tmpi runmpi 0 2 /tmp/tmp.1QBXkf7ysR ./fort


**********************************************************

Open MPI does not support recursive calls of mpirun

**********************************************************


**********************************************************

Open MPI does not support recursive calls of mpirun

**********************************************************


**********************************************************

Open MPI does not support recursive calls of mpirun

**********************************************************
Unknown MPI implementation. Only MPICH (and its derivatives) and OpenMPI are supported!
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------


**********************************************************

Open MPI does not support recursive calls of mpirun

**********************************************************
Unknown MPI implementation. Only MPICH (and its derivatives) and OpenMPI are supported!
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[61247,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

Let me emphasize I am using OpenMPI. But I still haven't reptyr installed.

**Comment by Azrael3000** [comment]
Please install reptyr and check if that helps.

**Comment by Azrael3000** [comment]
Closed due to winter cleaning

**Comment by nicolas-tardieu** [comment]
Dear Arno,
I gave a new try to tmpi on my new computer and, miracle, everything ran smoothly!
Thank you so much for providing this tool, which is a real game changer for me!
