### ISSUE TITLE
tmpi does not properly work with mpich 

### ISSUE THREAD

**Issue by PhilipVinc** [Azrael3000/tmpi#7]
I'm on fedora with mpich. See for example what happens with `tmpi 2 python` (spoiler: it reports size 1).

https://asciinema.org/a/HbRzLtMfjNoYaTh0zad4MOoeN

Instead using mpirun i get
```python
➜ mpirun -np 2 python -c "from mpi4py import MPI; print(MPI.COMM_WORLD.Get_size())"
2
2
```
Do you have any suggestion on what might be happening? maybe some env variables are slipping through?

**Comment by jczhang07** [comment]
@PhilipVinc A new PR is made (not merged yet) to support MPICH.  Try it and report problems to me. Thanks.

**Comment by Azrael3000** [comment]
@PhilipVinc if you ran a test please post here or in the pull request about the results

**Comment by PhilipVinc** [comment]
Give me a few hours and I will
Il 22 lug 2021, 08:51 +0200, Arno Mayrhofer ***@***.***>, ha scritto:

**Comment by Azrael3000** [comment]
@PhilipVinc did you get a chance to review it?

**Comment by PhilipVinc** [comment]
Sorry for the delay, i got a call and then left for holiday the day after...

I just tried #9 and it works fine!
Thanks a lot!

**Comment by Azrael3000** [comment]
No worries. Thanks for the feedback.
